# Challenge: Promotions

In this challenge, you'll develop codes to parse and analyze data returned from another API on Zalando such as [Promos homme (Men's Promotions)
](https://www.zalando.fr/promo-homme/) or [Promos femme (Women's Promotions)](https://www.zalando.fr/promo-femme/). The workflow is almost the same as in the guided lesson but you'll work with different data.

## Obtaining the link

Wrote your codes in the cell below to obtain the data from the API endpoint you choose. A recap of the workflow:

1. Examine the webpages and choose one that you want to work with.

1. Use Google Chrome's DevTools to inspect the XHR network requests. Find out the API endpoint that serves data to the webpage.

1. Test the API endpoint in the browser to verify its data.

1. Change the page number offset of the API URL to test if it's working.

In [2]:
import json
import requests as r
import pandas as pd
from pandas.io.json import json_normalize

In [5]:
url=f'https://www.zalando.fr/api/catalog/articles?categories=promo-femme&limit=84&offset=84&sort=sale'

headers= {'cookie': 'fvgs_ml=mosaic; Zalando-Client-Id=da264615-0823-403a-ac62-e0681c9b6146; _ga=GA1.2.1720755013.1566201630; _ga=GA1.2.1720755013.1566201630; _gid=GA1.2.1041020776.1566201631; _gac_UA-19190613-1=1.1566201631.CjwKCAjwkenqBRBgEiwA-bZVtkbfKuobZlLM67u6fOIUJjHGC82Fk4L14YMKedSg_vFphaNu85jp8xoCO6AQAvD_BwE; _gcl_aw=GCL.1566201631.CjwKCAjwkenqBRBgEiwA-bZVtkbfKuobZlLM67u6fOIUJjHGC82Fk4L14YMKedSg_vFphaNu85jp8xoCO6AQAvD_BwE; _gcl_dc=GCL.1566201631.CjwKCAjwkenqBRBgEiwA-bZVtkbfKuobZlLM67u6fOIUJjHGC82Fk4L14YMKedSg_vFphaNu85jp8xoCO6AQAvD_BwE; _gcl_au=1.1.652207347.1566201631; _fbp=fb.1.1566201631334.275443478; _abck=3FFF3905B47420A2F63AFCCB729EF58C~0~YAAQBv4BF0Rj6X5sAQAA+UHkqALVKwkcuuP/phuGQD3ddA9Q166zOX996Pl9hNzmon1sd0ZRDlLWsCCZMN91jLGjZVam7/CjIgDWlu3DlLhrplZIWXclYTf6vGK8Y4K2f8i6rZ6tfGsDMlEWJtDi9JzzEYQsUDwrMoJ0zBTMCtoOpSQ5YvR/YMzrJF6X28fbm46eGAawE2W2m3hmhKiqFPOnCs+W5teAajekWnW8RMKJfXJuo4hovY76eAxp09ekO2hpbknvQnyWlMvgeuUkKBlRr/64mLw67SvYOvNRad2ax7JklwBE7YA=~-1~-1~-1; bm_sz=BC971C275E26DD70088C35838E27E662~YAAQBv4BF/Lp6n5sAQAAbC3EqQTdgqRnyx7kO1jOSMNcFOR4Bic+NUh/PcDa1+dSvASYbJOp8CpOoMvlglmT7TKKSv2RpL9fJp90GyqUShWx2g5Hb2gHMxwKGPJNVP5hVaHhgjP3//27uzhtCRsxNPgG3uhYIswj8RTzjlIOsRvV3Frw2MY5laPCOPTEoCR9; frsx=AAAAAEiSi3j-uO-CvBiQ7TM9zXinRE8xXlcXmCxOw4dAYlB9Y5hq7O2S__5fOPbTTOIvDVJAaTWODwgdZeHSkUlOg8hMtnfhykGSgGcCujf92WGJ7geppbODtr5UnvMY-LzP6B1aFP41-HmSCSpsNF4=; bm_mi=67A3B42E66AAE2CC967C666DE4B85908~f8GdSsZOyp0D5J17gBXNr0Ce31i8hiCY7xNUbAi2t7JgJwndaWiBy15yd9hiy5EucEr/AcWrzqUfl0zvCuwfVhFyIXMN9HFyN+zLUxFXoA/aORTPtPG8Y1sxEy/4lajNIzLKH02rD930z/MwfGa7gsdhPR6yM3vdSrshR30XrPKvuFh6tOwbyi2huyE2tpbN6hyK4uzWYaT1PTahrRufgHD96YTukrMkjj+1WvML7h1kb9fn7UVa8lHze64Cl6ngqSs6iiOSAaSNuXWPHEiuzw/LEhWoYr4jhXOYEfpEp/o=; ncx=f; ak_bmsc=E4076B2442858F61E90523935420FB6B1701FE06453200006D905A5D2482A655~plhqXA4B/lgcssOZuWNhV3CejH6lEBcM59SwLrhGagZwdEjUg/ZC7S0oYlWbcnBR88u1izsAqV6VF4gjgcrvV4HtgscjgAg8tplyJLJ8X2wDqibpnTD1iYtW/ceayUov7YU9TQ6Jsa0DW5T1TvbmFeTUqHZciIIpDh4mXPs+IRxIMhYQyAOXp+PxSq86Q9qD2vCRc0u0VNQP3d4So2kSTEO1XGro4IjMxu4Auk18tPuSqlmK4V95xTTyQv1SU4aAfA; _gat_zalga=1',
'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36',
'x-xsrf-token': 'AAAAAEiSi3j-uO-CvBiQ7TM9zXinRE8xXlcXmCxOw4dAYlB9Y5hq7O2S__5fOPbTTOIvDVJAaTWODwgdZeHSkUlOg8hMtnfhykGSgGcCujf92WGJ7geppbODtr5UnvMY-LzP6B1aFP41-HmSCSpsNF4=',
'x-zalando-catalog-nakadi-context': '%7B%22previous_categories%22%3A%5B%22promo-femme%22%5D%2C%22previous_selected_filters%22%3A%5B%5D%2C%22preselected_filters%22%3A%5B%5D%7D',
'x-zalando-octopus-tests': '%5B%7B%22testName%22%3A%22mobile-filters-design%22%2C%22testVariant%22%3A%22mobile-light-filters%22%2C%22testFeedbackId%22%3A%2200000000-0000-0000-0000-000000000000%3A__EMPTY__%22%7D%2C%7B%22testName%22%3A%22image-test%22%2C%22testVariant%22%3A%22Test%20Variant%20B%20Test1%22%2C%22testFeedbackId%22%3A%2282baf50f-d236-47ea-a8f7-a36d388bca89%3Aclientid-da264615-0823-403a-ac62-e0681c9b6146%22%7D%2C%7B%22testName%22%3A%22teaser-card-test%22%2C%22testVariant%22%3A%22outward%22%2C%22testFeedbackId%22%3A%2200000000-0000-0000-0000-000000000000%3A__EMPTY__%22%7D%2C%7B%22testName%22%3A%22filter-cleanup-test%22%2C%22testVariant%22%3A%22sorting-as-dropdown%22%2C%22testFeedbackId%22%3A%22717403e6-fe98-4d17-9208-c9f40f1232b8%3Aclientid-da264615-0823-403a-ac62-e0681c9b6146%22%7D%5D'}

response=r.get(url,headers=headers)
result=response.json()
result

{'total_count': 95685,
 'pagination': {'page_count': 892, 'current_page': 2, 'per_page': 84},
 'sort': 'sale',
 'articles': [{'sku': 'OY181I08E-M11',
   'name': 'TROPICAL JUNGLE BRAZILIAN - Bas de bikini - green',
   'price': {'original': '15,99\xa0€',
    'promotional': '11,19\xa0€',
    'has_different_prices': False,
    'has_different_original_prices': False,
    'has_different_promotional_prices': False,
    'has_discount_on_selected_sizes_only': False},
   'sizes': ['S', 'M', 'L'],
   'url_key': 'oysho-tropical-jungle-brazilian-bas-de-bikini-green-oy181i08e-m11',
   'media': [{'path': 'OY/18/1I/08/EM/11/OY181I08E-M11@2.1.jpg',
     'role': 'DEFAULT',
     'packet_shot': False},
    {'path': 'OY/18/1I/08/EM/11/OY181I08E-M11@12.1.jpg',
     'role': 'HOVER',
     'packet_shot': False}],
   'brand_name': 'OYSHO',
   'is_premium': False,
   'family_articles': [{'sku': 'OY181I08E-M11',
     'url_key': 'oysho-tropical-jungle-brazilian-bas-de-bikini-green-oy181i08e-m11',
     'media': [{'path': 'OY/18/1I/08/EM/11/OY181I08E-M11@6.1.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'TROPICAL JUNGLE BRAZILIAN - Bas de bikini - green',
     'sizes': ['S', 'M', 'L'],
     'price': {'original': '15,99\xa0€',
      'promotional': '11,19\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': '-30%',
       'tracking_value': 'discount rate'}]}],
   'flags': [{'key': 'discountRate',
     'value': '-30%',
     'tracking_value': 'discount rate'}],
   'product_group': 'beach_wear'},
  {'sku': 'NM321G05D-Q11',
   'name': 'NMREKA LONG - Manteau court - black',
   'price': {'original': '49,99\xa0€',
    'promotional': '40,00\xa0€',
    'has_different_prices': False,
    'has_different_original_prices': False,
    'has_different_promotional_prices': False,
    'has_discount_on_selected_sizes_only': False},
   'sizes': ['36', '38', '40', '42'],
   'url_key': 'noisy-may-nmreka-long-blazer-nm321g05d-q11',
   'media': [{'path': 'NM/32/1G/05/DQ/11/NM321G05D-Q11@7.jpg',
     'role': 'DEFAULT',
     'packet_shot': False},
    {'path': 'NM/32/1G/05/DQ/11/NM321G05D-Q11@3.jpg',
     'role': 'HOVER',
     'packet_shot': False}],
   'brand_name': 'Noisy May',
   'is_premium': False,
   'family_articles': [{'sku': 'NM321G05D-Q11',
     'url_key': 'noisy-may-nmreka-long-blazer-nm321g05d-q11',
     'media': [{'path': 'NM/32/1G/05/DQ/11/NM321G05D-Q11@4.png',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'NMREKA LONG - Manteau court - black',
     'sizes': ['36', '38', '40', '42'],
     'price': {'original': '49,99\xa0€',
      'promotional': '40,00\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': '-20%',
       'tracking_value': 'discount rate'}]},
    {'sku': 'NM321G05D-C12',
     'url_key': 'noisy-may-nmreka-long-blazer-nm321g05d-c12',
     'media': [{'path': 'NM/32/1G/05/DC/12/NM321G05D-C12@12.png',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'NMREKA LONG - Manteau court - light grey melange',
     'sizes': ['36', '38', '40', '42', '44'],
     'price': {'original': '49,99\xa0€',
      'promotional': '49,99\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': []},
    {'sku': 'NM321G05D-C11',
     'url_key': 'noisy-may-nmreka-long-blazer-dark-grey-nm321g05d-c11',
     'media': [{'path': 'NM/32/1G/05/DC/11/NM321G05D-C11@2.png',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'NMREKA LONG - Manteau court - dark grey',
     'sizes': ['36', '38', '40', '42', '44'],
     'price': {'original': '49,99\xa0€',
      'promotional': '49,99\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': []}],
   'flags': [{'key': 'discountRate',
     'value': '-20%',
     'tracking_value': 'discount rate'}],
   'product_group': 'clothing'},
  {'sku': 'UR621A01A-C11',
   'name': 'LADIES CAMO TECH - Legging - grey',
   'price': {'original': '19,95\xa0€',
    'promotional': '14,00\xa0€',
    'has_different_prices': True,
    'has_different_original_prices': False,
    'has_different_promotional_prices': True,
    'has_discount_on_selected_sizes_only': False},
   'sizes': ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
   'url_key': 'urban-classics-ladies-tech-leggings-ur621a01a-c11',
   'media': [{'path': 'UR/62/1A/01/AC/11/UR621A01A-C11@8.jpg',
     'role': 'DEFAULT',
     'packet_shot': False},
    {'path': 'UR/62/1A/01/AC/11/UR621A01A-C11@9.jpg',
     'role': 'HOVER',
     'packet_shot': False}],
   'brand_name': 'Urban Classics',
   'is_premium': False,
   'family_articles': [{'sku': 'UR621A01A-C11',
     'url_key': 'urban-classics-ladies-tech-leggings-ur621a01a-c11',
     'media': [{'path': 'UR/62/1A/01/AC/11/UR621A01A-C11@10.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'LADIES CAMO TECH - Legging - grey',
     'sizes': ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
     'price': {'original': '19,95\xa0€',
      'promotional': '14,00\xa0€',
      'has_different_prices': True,
      'has_different_original_prices': False,
      'has_different_promotional_prices': True,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': 'Jusqu’à -30%',
       'tracking_value': 'discount rate'}]},
    {'sku': 'UR621A01A-M11',
     'url_key': 'urban-classics-ladies-tech-leggings-woodblack-ur621a01a-m11',
     'media': [{'path': 'UR/62/1A/01/AM/11/UR621A01A-M11@12.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'LADIES CAMO TECH - Legging - wood/black',
     'sizes': ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
     'price': {'original': '19,95\xa0€',
      'promotional': '18,00\xa0€',
      'has_different_prices': True,
      'has_different_original_prices': False,
      'has_different_promotional_prices': True,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': 'Jusqu’à -10%',
       'tracking_value': 'discount rate'}]},
    {'sku': 'UR621A01A-A11',
     'url_key': 'urban-classics-ladies-camo-tech-legging-ur621a01a-a11',
     'media': [{'path': 'UR/62/1A/01/AA/11/UR621A01A-A11@17.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'LADIES CAMO TECH - Legging - snowcamo',
     'sizes': ['XS', 'XL', 'XXL', '3XL', '4XL', '5XL'],
     'price': {'original': '32,90\xa0€',
      'promotional': '32,90\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': []}],
   'flags': [{'key': 'discountRate',
     'value': 'Jusqu’à -30%',
     'tracking_value': 'discount rate'}],
   'product_group': 'clothing'},
  {'sku': 'A0H12B00K-A11',
   'name': 'GEL-LYTE - Baskets basses - white',
   'price': {'original': '109,95\xa0€',
    'promotional': '75,00\xa0€',
    'has_different_prices': False,
    'has_different_original_prices': False,
    'has_different_promotional_prices': False,
    'has_discount_on_selected_sizes_only': False},
   'sizes': ['36',
    '37',
    '37.5',
    '38',
    '39',
    '39.5',
    '40',
    '40.5',
    '41.5',
    '42',
    '42.5',
    '43.5',
    '44',
    '44.5',
    '45',
    '46',
    '46.5',
    '47',
    '48',
    '49'],
   'url_key': 'asics-tiger-gel-lyte-baskets-basses-white-a0h12b00k-a11',
   'media': [{'path': 'A0/H1/2B/00/KA/11/A0H12B00K-A11@12.1.jpg',
     'role': 'DEFAULT',
     'packet_shot': True}],
   'brand_name': 'Asics Tiger',
   'is_premium': False,
   'family_articles': [{'sku': 'A0H12B00K-A11',
     'url_key': 'asics-tiger-gel-lyte-baskets-basses-white-a0h12b00k-a11',
     'media': [{'path': 'A0/H1/2B/00/KA/11/A0H12B00K-A11@12.1.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'GEL-LYTE - Baskets basses - white',
     'sizes': ['36',
      '37',
      '37.5',
      '38',
      '39',
      '39.5',
      '40',
      '40.5',
      '41.5',
      '42',
      '42.5',
      '43.5',
      '44',
      '44.5',
      '45',
      '46',
      '46.5',
      '47',
      '48',
      '49'],
     'price': {'original': '109,95\xa0€',
      'promotional': '75,00\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': '-32%',
       'tracking_value': 'discount rate'}]},
    {'sku': 'A0H12B00K-Q11',
     'url_key': 'asics-tiger-gel-lyte-baskets-basses-a0h12b00k-q11',
     'media': [{'path': 'A0/H1/2B/00/KQ/11/A0H12B00K-Q11@12.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'GEL-LYTE - Baskets basses - black',
     'sizes': ['36',
      '37',
      '37.5',
      '38',
      '39',
      '39.5',
      '40',
      '40.5',
      '41.5',
      '42',
      '42.5',
      '43.5',
      '44',
      '44.5',
      '45',
      '46',
      '46.5',
      '47',
      '48',
      '49'],
     'price': {'original': '109,95\xa0€',
      'promotional': '75,00\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': '-32%',
       'tracking_value': 'discount rate'},
      {'key': 'specialOffer',
       'value': 'Exclusivité',
       'tracking_value': 'special offer'}]}],
   'flags': [{'key': 'discountRate',
     'value': '-32%',
     'tracking_value': 'discount rate'}],
   'product_group': 'shoe'},
  {'sku': 'K4411A05C-K11',
   'name': 'Bottes - dark blue',
   'price': {'original': '109,99\xa0€',
    'promotional': '66,00\xa0€',
    'has_different_prices': True,
    'has_different_original_prices': False,
    'has_different_promotional_prices': True,
    'has_discount_on_selected_sizes_only': False},
   'sizes': ['36', '37', '38', '39', '40', '41', '42'],
   'url_key': 'kiomi-bottes-dark-blue-k4411a05c-k11',
   'media': [{'path': 'K4/41/1A/05/CK/11/K4411A05C-K11@14.jpg',
     'role': 'DEFAULT',
     'packet_shot': False}],
   'brand_name': 'KIOMI',
   'is_premium': False,
   'family_articles': [{'sku': 'K4411A05C-K11',
     'url_key': 'kiomi-bottes-dark-blue-k4411a05c-k11',
     'media': [{'path': 'K4/41/1A/05/CK/11/K4411A05C-K11@5.1.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'Bottes - dark blue',
     'sizes': ['36', '37', '38', '39', '40', '41', '42'],
     'price': {'original': '109,99\xa0€',
      'promotional': '66,00\xa0€',
      'has_different_prices': True,
      'has_different_original_prices': False,
      'has_different_promotional_prices': True,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': 'Jusqu’à -40%',
       'tracking_value': 'discount rate'}]}],
   'flags': [{'key': 'discountRate',
     'value': 'Jusqu’à -40%',
     'tracking_value': 'discount rate'}],
   'product_group': 'shoe'},
  {'sku': 'AD121J0FG-Q11',
   'name': 'ADICOLOR TREFOIL HOODIE - Sweat à capuche - black',
   'price': {'original': '59,95\xa0€',
    'promotional': '45,00\xa0€',
    'has_different_prices': True,
    'has_different_original_prices': False,
    'has_different_promotional_prices': True,
    'has_discount_on_selected_sizes_only': False},
   'sizes': ['32', '34', '36', '38', '40', '42', '44', '46', '48', '50'],
   'url_key': 'adidas-originals-trefoil-hoodie-sweatshirt-ad121j0fg-q11',
   'media': [{'path': 'AD/12/1J/0F/GQ/11/AD121J0FG-Q11@11.1.jpg',
     'role': 'DEFAULT',
     'packet_shot': False},
    {'path': 'AD/12/1J/0F/GQ/11/AD121J0FG-Q11@14.1.jpg',
     'role': 'HOVER',
     'packet_shot': False}],
   'brand_name': 'adidas Originals',
   'is_premium': False,
   'family_articles': [{'sku': 'AD121J0FG-Q11',
     'url_key': 'adidas-originals-trefoil-hoodie-sweatshirt-ad121j0fg-q11',
     'media': [{'path': 'AD/12/1J/0F/GQ/11/AD121J0FG-Q11@15.1.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'ADICOLOR TREFOIL HOODIE - Sweat à capuche - black',
     'sizes': ['32', '34', '36', '38', '40', '42', '44', '46', '48', '50'],
     'price': {'original': '59,95\xa0€',
      'promotional': '45,00\xa0€',
      'has_different_prices': True,
      'has_different_original_prices': False,
      'has_different_promotional_prices': True,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': 'Jusqu’à -25%',
       'tracking_value': 'discount rate'}]},
    {'sku': 'AD121J0FG-K11',
     'url_key': 'adidas-originals-trefoil-hoodie-sweatshirt-ad121j0fg-k11',
     'media': [{'path': 'AD/12/1J/0F/GK/11/AD121J0FG-K11@14.1.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'ADICOLOR TREFOIL HOODIE - Sweat à capuche - collegiate navy',
     'sizes': ['32', '34', '36', '38', '40', '42', '44', '46'],
     'price': {'original': '59,95\xa0€',
      'promotional': '59,95\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'specialOffer',
       'value': 'Exclusivité',
       'tracking_value': 'special offer'}]},
    {'sku': 'AD121J0FG-C11',
     'url_key': 'adidas-originals-trefoil-hoodie-sweatshirt-grey-ad121j0fg-c11',
     'media': [{'path': 'AD/12/1J/0F/GC/11/AD121J0FG-C11@14.1.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'ADICOLOR TREFOIL HOODIE - Sweat à capuche - grey',
     'sizes': ['32', '34', '36', '38', '40', '42', '44', '46', '48', '50'],
     'price': {'original': '59,95\xa0€',
      'promotional': '45,00\xa0€',
      'has_different_prices': True,
      'has_different_original_prices': False,
      'has_different_promotional_prices': True,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': 'Jusqu’à -25%',
       'tracking_value': 'discount rate'}]}],
   'flags': [{'key': 'discountRate',
     'value': 'Jusqu’à -25%',
     'tracking_value': 'discount rate'}],
   'product_group': 'clothing'},
  {'sku': 'AN611A0FQ-Q11',
   'name': 'Cuissardes - black',
   'price': {'original': '44,99\xa0€',
    'promotional': '27,00\xa0€',
    'has_different_prices': True,
    'has_different_original_prices': False,
    'has_different_promotional_prices': True,
    'has_discount_on_selected_sizes_only': False},
   'sizes': ['36', '37', '38', '39', '40', '41', '42'],
   'url_key': 'anna-field-daisy-cuissardes-black-an611a0fq-q11',
   'media': [{'path': 'AN/61/1A/0F/QQ/11/AN611A0FQ-Q11@15.1.jpg',
     'role': 'DEFAULT',
     'packet_shot': False}],
   'brand_name': 'Anna Field',
   'is_premium': False,
   'family_articles': [{'sku': 'AN611A0FQ-Q11',
     'url_key': 'anna-field-daisy-cuissardes-black-an611a0fq-q11',
     'media': [{'path': 'AN/61/1A/0F/QQ/11/AN611A0FQ-Q11@19.1.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'Cuissardes - black',
     'sizes': ['36', '37', '38', '39', '40', '41', '42'],
     'price': {'original': '44,99\xa0€',
      'promotional': '27,00\xa0€',
      'has_different_prices': True,
      'has_different_original_prices': False,
      'has_different_promotional_prices': True,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': 'Jusqu’à -40%',
       'tracking_value': 'discount rate'}]}],
   'flags': [{'key': 'discountRate',
     'value': 'Jusqu’à -40%',
     'tracking_value': 'discount rate'}],
   'product_group': 'shoe'},
  {'sku': 'AN611A0BB-Q11',
   'name': 'Ballerines - black',
   'price': {'original': '12,99\xa0€',
    'promotional': '9,10\xa0€',
    'has_different_prices': True,
    'has_different_original_prices': False,
    'has_different_promotional_prices': True,
    'has_discount_on_selected_sizes_only': False},
   'sizes': ['36', '37', '38', '39', '40', '41', '42'],
   'url_key': 'anna-field-ballerines-black-an611a0bb-q11',
   'media': [{'path': 'AN/61/1A/0B/BQ/11/AN611A0BB-Q11@18.1.jpg',
     'role': 'DEFAULT',
     'packet_shot': True}],
   'brand_name': 'Anna Field',
   'is_premium': False,
   'family_articles': [{'sku': 'AN611A0BB-Q11',
     'url_key': 'anna-field-ballerines-black-an611a0bb-q11',
     'media': [{'path': 'AN/61/1A/0B/BQ/11/AN611A0BB-Q11@18.1.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'Ballerines - black',
     'sizes': ['36', '37', '38', '39', '40', '41', '42'],
     'price': {'original': '12,99\xa0€',
      'promotional': '9,10\xa0€',
      'has_different_prices': True,
      'has_different_original_prices': False,
      'has_different_promotional_prices': True,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'discountRate',
       'value': 'Jusqu’à -30%',
       'tracking_value': 'discount rate'}]},
    {'sku': 'AN611A0BB-K13',
     'url_key': 'anna-field-ballerines-light-blue-an611a0bb-k13',
     'media': [{'path': 'AN/61/1A/0B/BK/13/AN611A0BB-K13@14.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'Ballerines - light blue',
     'sizes': ['36', '38', '39', '40', '41', '42'],
     'price': {'original': '12,95\xa0€',
      'promotional': '12,95\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'specialOffer',
       'value': 'Exclusivité',
       'tracking_value': 'special offer'}]},
    {'sku': 'AN611A0BB-G11',
     'url_key': 'anna-field-ballerines-red-an611a0bb-g11',
     'media': [{'path': 'AN/61/1A/0B/BG/11/AN611A0BB-G11@20.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'Ballerines - poppy red',
     'sizes': ['36', '37', '38', '39', '40', '41'],
     'price': {'original': '12,99\xa0€',
      'promotional': '12,99\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': []},
    {'sku': 'AN611A0BB-J11',
     'url_key': 'anna-field-ballerines-pink-an611a0bb-j11',
     'media': [{'path': 'AN/61/1A/0B/BJ/11/AN611A0BB-J11@14.jpg',
       'role': 'FAMILY',
       'packet_shot': True}],
     'name': 'Ballerines - pink',
     'sizes': ['36', '37', '38', '39', '40', '41', '42'],
     'price': {'original': '12,95\xa0€',
      'promotional': '12,95\xa0€',
      'has_different_prices': False,
      'has_different_original_prices': False,
      'has_different_promotional_prices': False,
      'has_discount_on_selected_sizes_only': False},
     'flags': [{'key': 'specialOffer',
       'value': 'Exclusivité',
       'tracking_value': 'special offer'}]}],
   'flags': [{'key': 'discountRate',
     'value': 'Jusqu’à -30%',
     'tracking_value': 'discount rate'}],
   'product_group': 'shoe'},
  {'sku': 'V1021G09D-K11',
   'name': 'Veste en jean - medium blue denim',
   'price': {'original': '59,99\xa0€',
    'promotional': '48,00\xa0€',
    'has_different_prices': False,
    'has_different_original_prices': False,
    'has_different_promotional_prices': False,

In [8]:
# your code here

number_of_loops=result['pagination']['page_count']
df=pd.DataFrame()
for i in range(number_of_loops):
    k=84*i
    url=f'https://www.zalando.fr/api/catalog/articles?categories=promo-femme&limit=84&offset={k}&sort=sale'
    response=r.get(url, headers=headers)
    result=response.json()
    flattened_data=json_normalize(result)
    flattened_data=json_normalize(flattened_data.articles[0])
    flattened_data=flattened_data.set_index('sku')
    df=df.append(flattened_data)
    if i%10==0:
        time.sleep(10)
df

C:\Users\anast\Anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,amount,brand_name,family_articles,flags,is_premium,media,name,outfits,price.base_price,price.has_different_original_prices,...,price.has_different_promotional_prices,price.has_discount_on_selected_sizes_only,price.original,price.promotional,product_group,sizes,tracking_information.impression_beacon,tracking_information.metrigo_impression_urls,tracking_information.source,url_key
sku,,,,,,,,,,,,,,,,,,,,,
UN241E0AV-Q11,NaN,Under Armour,"[{'sku': 'UN241E0AV-Q11', 'url_key': 'under-ar...","[{'key': 'sponsored', 'value': 'Sponsorisé', '...",False,[{'path': 'UN/24/1E/0A/VQ/11/UN241E0AV-Q11@8.j...,RIVAL SPORTSTYLE GRAPHIC PANT - Pantalon de su...,NaN,NaN,False,...,False,False,"44,95 €","40,00 €",clothing,"[XS, S, M, L, XL, XXL]",https://ccp-et.metrigo.zalan.do/event/sbv?z=da...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,under-armour-rival-sportstyle-graphic-pant-pan...
M3221C0L6-O11,NaN,mint&berry,"[{'sku': 'M3221C0L6-O11', 'url_key': 'mintandb...","[{'key': 'sponsored', 'value': 'Sponsorisé', '...",False,[{'path': 'M3/22/1C/0L/6O/11/M3221C0L6-O11@18....,Robe d'été - pink,NaN,NaN,False,...,False,False,"64,95 €","50,00 €",clothing,"[34, 36, 38, 40, 42, 44]",https://ccp-et.metrigo.zalan.do/event/sbv?z=da...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,mintandberry-robe-dete-pink-m3221c0l6-o11
UN241I030-Q11,NaN,Under Armour,"[{'sku': 'UN241I030-Q11', 'url_key': 'under-ar...","[{'key': 'sponsored', 'value': 'Sponsorisé', '...",False,[{'path': 'UN/24/1I/03/0Q/11/UN241I030-Q11@13....,RUSH BRA - Soutien-gorge de sport - black/tonal,NaN,NaN,False,...,True,False,"49,95 €","35,00 €",underwear,"[XS, S, M, L, XL]",https://ccp-et.metrigo.zalan.do/event/sbv?z=da...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,under-armour-rush-bra-soutien-gorge-de-sport-u...
CO415N03F-A11,NaN,Converse,"[{'sku': 'CO415N03F-A11', 'url_key': 'converse...","[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'CO/41/5N/03/FA/11/CO415N03F-A11@1.1...,CHUCK TAYLOR ALL STAR HI - Baskets montantes -...,NaN,NaN,False,...,False,False,"69,95 €","55,95 €",shoe,"[35, 36, 36.5, 37, 37.5, 38, 39, 39.5, 40, 41,...",NaN,NaN,NaN,converse-chuck-taylor-all-star-hi-baskets-mont...
NI121A05R-Q11,NaN,Nike Sportswear,"[{'sku': 'NI121A05R-Q11', 'url_key': 'nike-spo...","[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'NI/12/1A/05/RQ/11/NI121A05R-Q11@8.j...,CLUB LOGO - Legging - black,NaN,NaN,False,...,False,False,"24,95 €","20,00 €",clothing,"[XS, S, M, L, XL]",NaN,NaN,NaN,nike-sportswear-club-logo2-leggings-ni121a05r-q11
NE211A094-D11,NaN,New Balance,"[{'sku': 'NE211A094-D11', 'url_key': 'new-bala...","[{'key': 'discountRate', 'value': '-33%', 'tra...",False,[{'path': 'NE/21/1A/09/4D/11/NE211A094-D11@11....,GW500 - Baskets basses - metallic silver,NaN,NaN,False,...,False,False,"74,95 €","50,00 €",shoe,"[36, 36.5, 37, 37.5, 38, 39, 40, 40.5, 41, 41.5]",NaN,NaN,NaN,new-balance-gw500-baskets-basses-metallic-silv...
CO415B09I-A11,NaN,Converse,"[{'sku': 'CO415B09I-A11', 'url_key': 'converse...","[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'CO/41/5B/09/IA/11/CO415B09I-A11@21....,Baskets basses - white,NaN,NaN,False,...,False,False,"64,95 €","51,95 €",shoe,"[36, 36.5, 37, 37.5, 38, 39, 39.5, 40, 41, 41....",NaN,NaN,NaN,converse-baskets-basses-white-co415b09i-a11
NI111A0D7-B11,NaN,Nike Sportswear,"[{'sku': 'NI111A0D7-B11', 'url_key': 'nike-spo...","[{'key': 'discountRate', 'value': 'Jusqu’à -32...",False,[{'path': 'NI/11/1A/0D/7B/11/NI111A0D7-B11@3.j...,AF1 SAGE - Baskets basses - desert ore/white,NaN,NaN,False,...,True,False,"109,95 €","75,00 €",shoe,"[36, 36.5, 37.5, 38, 38.5, 39, 40, 40.5, 41, 4...",NaN,NaN,NaN,nike-sportswear-af1-sage-baskets-basses-ni111a...
AN611E015-Q11,NaN,Anna Field,"[{'sku': 'AN611E015-Q11', 'url_key': 'anna-fie...",[],False,[{'path': 'AN/61/1E/01/5Q/11/AN611E015-Q11@13....,Derbies - black,NaN,NaN,False,...,False,False,"39,99 €","39,99 €",shoe,"[36, 37, 38, 39, 40, 41, 42]",NaN,NaN,NaN,anna-field-derbies-black-an611e015-q11
NI121A09O-G11,NaN,Nike Sportswear,"[{'sku': 'NI121A09O-G11', 'url_key': 'nike-spo...","[{'key': 'discountRate', 'value': '-10%', 'tra...",False,[{'path': 'NI/12/1A/09/OG/11/NI121A09O-G11@4.j...,PANT - Pantalon de survêtement - team red/white,NaN,NaN,False,...,False,False,"39,95 €","36,00 €",clothing,"[XS, S, M, L, XL, XXL]",NaN,NaN,NaN,nike-sportswear-pant-pantalon-de-survetement-t...
RE011S03V-A11,NaN,Reebok Classic,"[{'sku': 'RE011S03V-A11', 'url_key': 'reebok-c...","[{'key': 'discountRate', 'value': 'Jusqu’à -15...",False,[{'path': 'RE/01/1S/03/VA/11/RE011S03V-A11@13....,PRINCESS - Baskets basses - white,NaN,NaN,False,...,True,False,"69,95 €","59,45 €",shoe,"[35, 35.5, 36, 37, 37.5, 38.5, 39, 40, 41, 42,...",NaN,NaN,NaN,reebok-classic-princess-baskets-basses-re011s0...
NI121A09Q-Q11,NaN,Nike Sportswear,"[{'sku': 'NI121A09Q-Q11', 'url_key': 'nike-spo...","[{'key': 'discountRate', 'value': '-11%', 'tra...",False,[{'path': 'NI/12/1A/09/QQ/11/NI121A09Q-Q11@8.j...,LEGASEE FLIP - Legging - black/racer blue,NaN,NaN,False,...,False,False,"34,95 €","31,00 €",clothing,"[XS, S, M, L, XL, XXL]",NaN,NaN,NaN,nike-sportswear-legasee-legging-blackracer-blu...
PU111A0EB-Q11,NaN,Puma,"[{'sku': 'PU111A0EB-Q11', 'url_key': 'puma-vik...","[{'key': 'discountRate', 'value': '-58%', 'tra...",False,[{'path': 'PU/11/1A/0E/BQ/11/PU111A0EB-Q11@4.1...,VIKKY RIBBON WOMEN'S TRAINERS - Baskets basse...,NaN,NaN,False,...,False,False,"60,00 €","25,00 €",shoe,"[35.5, 36, 37, 37.5, 38, 38.5, 39, 40]",NaN,NaN,NaN,puma-vikky-ribbon-womens-trainers-baskets-bass...
AD115B01Y-A11,NaN,adidas Originals,"[{'sku': 'AD115B01Y-A11', 'url_key': 'adidas-o...","[{'key': 'discountRate', 'value': 'Jusqu’à -20...",False,[{'path': 'AD/11/5B/01/YA/11/AD115B01Y-A11@12....,SUPERSTAR - Baskets basses - white/core black,NaN,NaN,False,...,True,False,"99,95 €","80,00 €",shoe,"[36, 38, 40, 42, 44, 46, 48, 50, 36 2/3, 37 1/...",NaN,NaN,NaN,adidas-originals-baskets-basses-white-core-bla...
CO411A0BD-002,NaN,Converse,"[{'sku': 'CO411A0BD-002', 'url_key': 'converse...","[{'key': 'discountRate', 'value': '-7%', 'trac...",False,[{'path': 'CO/41/1A/0B/D0/02/CO411A0BD-002@118...,CHUCK TAYLOR ALL STAR HI - Baskets montantes -...,"[{'id': 'ECSZIgIZRCW', 'url_key': '/outfits/EC...",NaN,False,...,False,False,"69,95 €","65,00 €",shoe,"[35, 36, 36.5, 37, 37.5, 38, 39, 39.5, 40, 41,...",NaN,NaN,NaN,converse-baskets-montantes-blanc-co411a0bd-002
AN611A0A9-Q11,NaN,Anna Field,"[{'sku': 'AN611A0A9-Q11', 'url_key': 'anna-fie...","[{'key': 'sponsored', 'value': 'Sponsorisé', '...",False,[{'path': 'AN/61/1A/0A/9Q/11/AN611A0A9-Q11@20....,Escarpins à plateforme - black,NaN,NaN,False,...,True,False,"31,99 €","19,20 €",shoe,"[36, 37, 38, 39, 40, 41, 42]",https://ccp-et.metrigo.zalan.do/event/sbv?z=da...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,anna-field-escarpins-noir-an611a0a9-q11
UN241G02V-Q11,NaN,Under Armour,"[{'sku': 'UN241G02V-Q11', 'url_key': 'under-ar...","[{'key': 'sponsored', 'value': 'Sponsorisé', '...",False,[{'path': 'UN/24/1G/02/VQ/11/UN241G02V-Q11@19....,FULL ZIP - Veste de survêtement - black/white,NaN,NaN,False,...,False,False,"69,95 €","56,51 €",clothing,"[XS, S, M, L, XL]",https://ccp-et.metrigo.zalan.do/event/sbv?z=da...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,under-armour-full-zip-veste-de-survetement-bla...
UN241D00M-Q11,NaN,Under Armour,"[{'sku': 'UN241D00M-Q11', 'url_key': 'under-ar...","[{'key': 'sponsored', 'value': 'Sponsorisé', '...",False,[{'path': 'UN/24/1D/00/MQ/11/UN241D00M-Q11@30....,TECH - T-shirt basique - black/metallic silver,NaN,NaN,False,...,False,False,"24,95 €","21,00 €",clothing,"[XS, S, M, L, XL, XXL]",https://ccp-et.metrigo.zalan.do/event/sbv?z=da...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,under-armour-tech-t-shirt-de-sport-un241d00m-q11
ZI111NA47-Q11,NaN,Zign,"[{'sku': 'ZI111NA47-Q11', 'url_key': 'zign-boo...","[{'key': 'discountRate', 'value': 'Jusqu’à -60...",False,[{'path': 'ZI/11/1N/A4/7Q/11/ZI111NA47-Q11@13....,Bottines à talons hauts - black,NaN,NaN,False,...,True,False,"109,99 €","44,00 €",shoe,"[36, 37, 38, 39, 40, 41, 42]",NaN,NaN,NaN,zign-boots-a-talons-black-zi111na47-q11
OY121C03G-G11,NaN,OYSHO,"[{'sku': 'OY121C03G-G11', 'url_key': 'oysho-ro...","[{'key': 'discountRate', 'value': '-30%', 'tra...",False,[{'path': 'OY/12/1C/03/GG/11/OY121C03G-G11@17....,Robe d'été - red,NaN,NaN,False,...,False,False,"29,99 €","20,99 €",clothing,"[XS, M, L]",NaN,NaN,NaN,oysho-robe-de-soiree-red-oy121c03g-g11
CO411A003-802,NaN,Converse,"[{'sku': 'CO411A003-802', 'url_key': 'converse...","[{'key': 'discountRate', 'value': '-8%', 'trac...",False,[{'path': 'CO/41/1A/00/38/02/CO411A003-802@19....,CHUCK TAYLOR ALL STAR OX - Baskets basses - black,"[{'id': 'pZ2Kb7ReQYy', 'url_key': '/outfits/pZ...",NaN,False,...,False,False,"64,95 €","60,00 €",shoe,"[35, 36, 36.5, 37, 37.5, 38, 39, 39.5, 40, 41,...",NaN,NaN,NaN,converse-as-ox-can-baskets-noir-co411a003-802
NE211A02Y-A11,NaN,New Balance,"[{'sku': 'NE211A02Y-A11', 'url_key': 'new-bala...","[{'key': 'discountRate', 'value': 'Jusqu’à -29...",False,[{'path': 'NE/21/1A/02/YA/11/NE211A02Y-A11@13....,WL574 - Baskets basses - white,NaN,NaN,False,...,True,False,"99,95 €","70,55 €",shoe,"[35, 36, 36.5, 37, 37.5, 38, 39, 40, 40.5, 42.5]",NaN,NaN,NaN,new-balance-wl574-baskets-basses-ne211a02y-a11
PU111A0DP-A11,NaN,Puma,"[{'sku': 'PU111A0DP-A11', 'url_key': 'puma-bas...","[{'key': 'discountRate', 'value': '-30%', 'tra...",False,[{'path': 'PU/11/1A/0D/PA/11/PU111A0DP-A11@15....,Baskets basses - white,NaN,NaN,False,...,False,False,"90,00 €","63,00 €",shoe,"[36, 37, 37.5, 38, 38.5, 39, 40.5, 41]",NaN,NaN,NaN,puma-baskets-basses-white-pu111a0dp-a11
RE011S01A-A11,NaN,Reebok Classic,"[{'sku': 'RE011S01A-A11', 'url_key': 'reebok-c...","[{'key': 'discountRate', 'value': 'Jusqu’à -30...",False,[{'path': 'RE/01/1S/01/AA/11/RE011S01A-A11@13....,CLASSIC LEATHER NYLON - Baskets basses - white...,NaN,NaN,False,...,True,False,"69,95 €","49,00 €",shoe,"[35, 35.5, 36, 37, 37.5, 38.5, 39, 40, 40.5, 4...",NaN,NaN,NaN,reebok-classic-baskets-basses-white-light-grey...
NL011A0LH-F11,NaN,New Look,"[{'sku': 'NL011A0LH-F11', 'url_key': 'new-look...","[{'key': 'discountRate', 'value': '-40%', 'tra...",False,[{'path': 'NL/01/1A/0L/HF/11/NL011A0LH-F11@10....,FIESTA - Mules - rose gold,NaN,NaN,False,...,False,False,"14,99 €","9,00 €",shoe,"[36, 37, 38, 39, 41, 42]",NaN,NaN,NaN,new-look-fiesta-mules-rose-gold-nl011a0lh-f11
NI111A0DD-K12,NaN,Nike Sportswear,"[{'sku': 'NI111A0DD-K12', 'url_key': 'nike-spo...","[{'key': 'discountRate', 'value': '-31%', 'tra...",False,[{'path': 'NI/11/1A/0D/DK/12/NI111A0DD-K12@9.j...,REACT 55 - Baskets basses - ocean cube/amethys...,NaN,NaN,False,...,False,False,"129,95 €","90,00 €",shoe,"[35.5, 36, 36.5, 37.5, 38, 38.5, 39, 40, 40.5,...",NaN,NaN,NaN,nike-sportswear-react-element-55-baskets-basse...
VE121N0DF-C11,NaN,Vero Moda,"[{'sku': 'VE121N0DF-C11', 'url_key': 'vero-mod...","[{'key': 'discountRate', 'value': 'Jusqu’à -35...",False,[{'path': 'VE/12/1N/0D/FC/11/VE121N0DF-C11@15....,VMSOPHIA - Jeans Skinny - dark grey denim,NaN,NaN,False,...,True,False,"34,99 €","22,75 €",clothing,"[36x30, 36x32, 36x34, 38x30, 38x32, 38x34, 40x...",NaN,NaN,NaN,vero-moda-vmsophia-jeans-skinny-dark-grey-deni...
1FI21D009-K12,NaN,Fila,"[{'sku': '1FI21D009-K12', 'url_key': 'fila-all...","[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': '1F/I2/1D/00/9K/12/1FI21D009-K12@4.j...,ALLISON TEE - T-shirt imprimé - black iris/tru...,NaN,NaN,False,...,False,False,"34,95 €","27,95 €",clothing,"[XS, S, M, L, XL]",NaN,NaN,NaN,fila-allison-tee-t-shirt-imprime-1fi21d009-k12
C0T21D00P-Q11,NaN,Champion Reverse Weave,"[{'sku': 'C0T21D00P-Q11', 'url_key': 'champion...","[{'key': 'discountRate', 'value': '-31%', 'tra...",False,[{'path': 'C0/T2/1D/00/PQ/11/C0T21D00P-Q11@8.j...,CREWNECK - T-shirt imprimé - black,NaN,NaN,False,...,False,False,"44,95 €","31,00 €",clothing,"[XS, S, M, L, XL]",NaN,NaN,NaN,champion-reverse-weave-crewneck-t-shirt-imprim...
AD121D0HV-Q11,NaN,adidas Originals,"[{'sku': 'AD121D0HV-Q11', 'url_key': 'adidas-o...","[{'key': 'discountRate', 'value': 'Jusqu’à -16...",False,[{'path': 'AD/12/1D/0H/VQ/11/AD121D0HV-Q11@13....,TREFOIL TEE - T-shirt imprimé - black,NaN,NaN,False,...,True,False,"24,95 €","21,00 €",clothing,"[32, 34, 36, 38, 40, 42, 44, 46]",NaN,NaN,NaN,adidas-originals-t-shirt-imprime-black-ad121d0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MT711A02Q-J11,NaN,mtng,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'MT/71/1A/02/QJ/11/MT711A02Q-J11@12....,Baskets basses - soto nude/nude/miami nude/dra...,NaN,NaN,False,...,False,False,"54,95 €","43,95 €",shoe,[39],NaN,NaN,NaN,mtng-baskets-basses-soto-nudenudemiami-nudedra...
M0Q21C11D-Q11,NaN,Missguided,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'M0/Q2/1C/11/DQ/11/M0Q21C11D-Q11@10....,FLORAL HIGH NECK TRIM TEA DRESS - Robe de soir...,NaN,NaN,False,...,False,False,"39,99 €","32,00 €",clothing,[36],NaN,NaN,NaN,missguided-floral-high-neck-trim-tea-dress-rob...
C0K21C03V-Q11,NaN,Club Monaco,[],"[{'key': 'discountRate', 'value': '-50%', 'tra...",True,[{'path': 'C0/K2/1C/03/VQ/11/C0K21C03V-Q11@8.j...,ARNETTIE DRESS - Robe pull - black/multi,NaN,NaN,False,...,False,False,"249,95 €","124,95 €",clothing,[36],NaN,NaN,NaN,club-monaco-arnettie-dress-robe-pull-blackmult...
R5921C04F-K11,NaN,Ragwear,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'R5/92/1C/04/FK/11/R5921C04F-K11@11....,Robe en jersey - blue,NaN,NaN,False,...,False,False,"54,95 €","43,95 €",clothing,[L],NaN,NaN,NaN,ragwear-robe-dete-blue-r5921c04f-k11
TID21C00I-A11,NaN,Tiger Mist,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'TI/D2/1C/00/IA/11/TID21C00I-A11@14....,ELSIE DRESS - Robe d'été - white,NaN,NaN,False,...,False,False,"99,95 €","79,95 €",clothing,[L],NaN,NaN,NaN,tiger-mist-elsie-dress-robe-dete-white-tid21c0...
G1111A01Q-G11,NaN,Gabriele,[],"[{'key': 'discountRate', 'value': '-40%', 'tra...",False,[{'path': 'G1/11/1A/01/QG/11/G1111A01Q-G11@3.1...,STEFY - Ballerines - rosso,NaN,NaN,False,...,False,False,"149,95 €","90,00 €",shoe,[39.5],NaN,NaN,NaN,gabriele-stefy-ballerines-g1111a01q-g11
CR221I07V-C11,NaN,Cream,[],"[{'key': 'discountRate', 'value': '-40%', 'tra...",False,[{'path': 'CR/22/1I/07/VC/11/CR221I07V-C11@8.j...,TAMMY CARDIGAN - Gilet - light grey melange,NaN,NaN,False,...,False,False,"59,95 €","35,95 €",clothing,[XXL],NaN,NaN,NaN,cream-tammy-cardigan-gilet-cr221i07v-c11
S0011A00W-Q11,NaN,Senso,[],"[{'key': 'discountRate', 'value': '-50%', 'tra...",True,[{'path': 'S0/01/1A/00/WQ/11/S0011A00W-Q11@14....,LANI - Sandales - ebony,NaN,NaN,False,...,False,False,"219,95 €","110,00 €",shoe,"[38, 40]",NaN,NaN,NaN,senso-lani-sandales-ebony-s0011a00w-q11
SE321S003-A11,NaN,See by Chloé,[],"[{'key': 'discountRate', 'value': '-35%', 'tra...",True,[{'path': 'SE/32/1S/00/3A/11/SE321S003-A11@8.j...,Short en jean - white,NaN,NaN,False,...,False,False,"209,95 €","135,95 €",clothing,"[40, 44]",NaN,NaN,NaN,see-by-chloe-short-en-jean-white-se321s003-a11
TO311A012-O11,NaN,TOMS,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'TO/31/1A/01/2O/11/TO311A012-O11@9.j...,SICILY - Sandales - natural,NaN,NaN,False,...,False,False,"69,95 €","55,95 €",shoe,"[36, 37]",NaN,NaN,NaN,toms-sicily-sandales-to311a012-o11
OA121U01Y-G11,NaN,Oakwood,[],"[{'key': 'discountRate', 'value': '-35%', 'tra...",False,[{'path': 'OA/12/1U/01/YG/11/OA121U01Y-G11@6.j...,MANON - Veste en cuir - red,NaN,NaN,False,...,False,False,"229,95 €","148,95 €",clothing,[L],NaN,NaN,NaN,oakwood-manon-veste-en-cuir-red-oa121u01y-g11
PIG11N003-C11,NaN,Pier One Wide Fit,[],"[{'key': 'discountRate', 'value': '-60%', 'tra...",False,[{'path': 'PI/G1/1N/00/3C/11/PIG11N003-C11@4.j...,WIDE FIT - Boots à talons - grey,NaN,NaN,False,...,False,False,"69,99 €","28,00 €",shoe,[39],NaN,NaN,NaN,pier-one-wide-fit-wide-fit-boots-a-talons-grey...
WD221U03R-K11,NaN,Schmuddelwedda,[],"[{'key': 'discountRate', 'value': '-26%', 'tra...",False,[{'path': 'WD/22/1U/03/RK/11/WD221U03R-K11@2.1...,REGEN - Parka - dark blue,NaN,NaN,False,...,False,False,"259,95 €","193,55 €",clothing,[S],NaN,NaN,NaN,schmuddelwedda-regen-veste-impermeable-dark-bl...
GA111A0UT-C11,NaN,Gabor,[],"[{'key': 'discountRate', 'value': '-35%', 'tra...",False,[{'path': 'GA/11/1A/0U/TC/11/GA111A0UT-C11@3.j...,WIDE FIT - Baskets basses - light grey,NaN,NaN,False,...,False,False,"119,95 €","77,95 €",shoe,"[35, 42.5]",NaN,NaN,NaN,gabor-wide-fit-baskets-basses-light-grey-ga111...
VE121G0OU-C11,NaN,Vero Moda,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'VE/12/1G/0O/UC/11/VE121G0OU-C11@16....,VMNANCY SHORT - Gilet - medium grey melange,NaN,NaN,False,...,False,False,"29,99 €","24,00 €",clothing,[S],NaN,NaN,NaN,vero-moda-vmnancy-short-gilet-ve121g0ou-c11
NX321B026-Q12,NaN,Next,[],"[{'key': 'discountRate', 'value': '-50%', 'tra...",False,[{'path': 'NX/32/1B/02/6Q/12/NX321B026-Q12@8.1...,Minijupe - anthracite,NaN,NaN,False,...,False,False,"22,00 €","11,00 €",clothing,"[40, 46]",NaN,NaN,NaN,next-minijupe-anthracite-nx321b026-q12
VD211A00S-J11,NaN,Vidorreta,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'VD/21/1A/00/SJ/11/VD211A00S-J11@12....,Sandales à plateforme - nude,NaN,NaN,False,...,False,False,"79,95 €","63,95 €",shoe,[41],NaN,NaN,NaN,vidorreta-sandales-compensees-nude-vd211a00s-j11
DR221C00U-K11,NaN,DRYKORN,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",True,[{'path': 'DR/22/1C/00/UK/11/DR221C00U-K11@10....,SERINA - Robe d'été - blue,NaN,NaN,False,...,False,False,"149,95 €","119,95 €",clothing,[40],NaN,NaN,NaN,drykorn-serina-robe-dete-dr221c00u-k11
5BI11B006-B11,NaN,Bibi Lou,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': '5B/I1/1B/00/6B/11/5BI11B006-B11@3.j...,Escarpins à talons hauts - taupe,NaN,NaN,False,...,False,False,"119,95 €","95,95 €",shoe,[36],NaN,NaN,NaN,bibi-lou-escarpins-taupe-5bi11b006-b11
MF921S03U-A11,NaN,Miss Selfridge,[],"[{'key': 'discountRate', 'value': '-30%', 'tra...",False,[{'path': 'MF/92/1S/03/UA/11/MF921S03U-A11@8.1...,FLAT FRONT - Short - ivory,NaN,NaN,False,...,False,False,"41,95 €","29,36 €",clothing,[40],NaN,NaN,NaN,miss-selfridge-flat-front-short-ivory-mf921s03...
AD741G01A-Q11,NaN,adidas by Stella McCartney,[],"[{'key': 'discountRate', 'value': '-30%', 'tra...",False,[{'path': 'AD/74/1G/01/AQ/11/AD741G01A-Q11@4.j...,CROP - Pantalon de survêtement - black,NaN,NaN,False,...,False,False,"129,95 €","90,95 €",clothing,[S],NaN,NaN,NaN,adidas-by-stella-mccartney-crop-pantalon-de-su...
SG721C0BJ-J11,NaN,Swing,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'SG/72/1C/0B/JJ/11/SG721C0BJ-J11@6.j...,Robe de cocktail - peach,NaN,NaN,False,...,False,False,"189,95 €","151,95 €",clothing,"[40, 42]",NaN,NaN,NaN,swing-robe-de-cocktail-peach-sg721c0bj-j11
HU315A00N-A11,NaN,Hummel,[],"[{'key': 'discountRate', 'value': '-40%', 'tra...",False,[{'path': 'HU/31/5A/00/NA/11/HU315A00N-A11@5.j...,SLIMMER STADIL - Baskets basses - white/green,NaN,NaN,False,...,False,False,"64,95 €","38,95 €",shoe,[47],NaN,NaN,NaN,hummel-slimmer-stadil-baskets-basses-hu315a00n...
KP111A00F-F11,NaN,Katy Perry,[],"[{'key': 'discountRate', 'value': '-45%', 'tra...",False,[{'path': 'KP/11/1A/00/FF/11/KP111A00F-F11@7.j...,THE GELI - Tongs - champagne,NaN,NaN,False,...,False,False,"74,95 €","40,95 €",shoe,[36],NaN,NaN,NaN,katy-perry-the-geli-tongs-kp111a00f-f11
VEB21U00S-B11,NaN,Vero Moda Tall,[],"[{'key': 'discountRate', 'value': '-25%', 'tra...",False,[{'path': 'VE/B2/1U/00/SB/11/VEB21U00S-B11@4.1...,VMRAMBLA CALA - Manteau classique - café au lait,NaN,NaN,False,...,False,False,"64,99 €","48,45 €",clothing,[S],NaN,NaN,NaN,vero-moda-tall-vmrambla-cala-manteau-classique...

## Reading the data

In the next cell, use Python to obtain data from the API endpoint you chose in the previous step. Workflow:

1. Import libraries.

1. Define the initial API endpoint URL.

1. Make request to obtain data of the 1st page. Flatten the data and store it in an empty object variable.

1. Find out the total page count in the 1st page data.

1. Use a FOR loop to make requests for the additional pages from 2 to page count. Append the data of each additional page to the flatterned data object.

1. Print and review the data you obtained.

In [ ]:
# your code here

## Bonus

Extract the following information from the data:

* The trending brand.

* The product(s) with the highest discount.

* The sum of discounts of all goods (sum_discounted_prices divided by sum_original_prices).

In [9]:
# your code here

df.brand_name.value_counts()

Anna Field                  1940
Even&Odd                    1769
Dorothy Perkins             1142
ONLY                        1133
New Look                     983
Esprit                       973
KIOMI                        919
mint&berry                   883
Vero Moda                    879
Topshop                      784
Vila                         711
River Island                 675
Tamaris                      641
PULL&BEAR                    616
s.Oliver                     595
TOM TAILOR                   591
Nike Performance             583
Next                         561
Missguided                   555
Puma                         546
Tommy Hilfiger               531
Marc O'Polo                  521
Monki                        514
TWINTIP                      500
Miss Selfridge               479
edc by Esprit                465
Pieces                       460
Kaffe                        444
Lauren Ralph Lauren          407
Pepe Jeans                   405
                            ...
Darkwood                       1
Adidas Timing                  1
Crumpler                       1
White Mountaineering           1
Osprey                         1
Oakley                         1
HAX                            1
Djinn's                        1
La Sportiva                    1
L'Oréal Paris                  1
Versace Jeans Couture          1
Greenburry                     1
Esprit Petite                  1
mint&berry wide fit            1
Versace Watches                1
Harold's                       1
3.1 Phillip Lim                1
Baby-G                         1
Roosevelt                      1
Egyptian Magic                 1
Art                            1
Mister Tee                     1
Lässig                         1
MAI PIÙ SENZA                  1
Crickit                        1
Killtec                        1
Neil Barrett                   1
Mackintosh                     1
Blowfish                       1
Esprit Collection Petite       1
Name: brand_name, Length: 1257, dtype: int64

In [10]:
df['price_original']=df['price.original'].str.extract('(\d+,\d*)')
df['price_promotional']=df['price.promotional'].str.extract('(\d+,\d*)')
df[['price_original','price_promotional']]

              price_original price_promotional
sku
UN241E0AV-Q11          44,95             40,00
M3221C0L6-O11          64,95             50,00
UN241I030-Q11          49,95             35,00
CO415N03F-A11          69,95             55,95
NI121A05R-Q11          24,95             20,00
NE211A094-D11          74,95             50,00
CO415B09I-A11          64,95             51,95
NI111A0D7-B11         109,95             75,00
AN611E015-Q11          39,99             39,99
NI121A09O-G11          39,95             36,00
RE011S03V-A11          69,95             59,45
NI121A09Q-Q11          34,95             31,00
PU111A0EB-Q11          60,00             25,00
AD115B01Y-A11          99,95             80,00
CO411A0BD-002          69,95             65,00
AN611A0A9-Q11          31,99             19,20
UN241G02V-Q11          69,95             56,51
UN241D00M-Q11          24,95             21,00
ZI111NA47-Q11         109,99             44,00
OY121C03G-G11          29,99             20,99
CO411A003-802          64,95             60,00
NE211A02Y-A11          99,95             70,55
PU111A0DP-A11          90,00             63,00
RE011S01A-A11          69,95             49,00
NL011A0LH-F11          14,99              9,00
NI111A0DD-K12         129,95             90,00
VE121N0DF-C11          34,99             22,75
1FI21D009-K12          34,95             27,95
C0T21D00P-Q11          44,95             31,00
AD121D0HV-Q11          24,95             21,00
...                      ...               ...
MT711A02Q-J11          54,95             43,95
M0Q21C11D-Q11          39,99             32,00
C0K21C03V-Q11         249,95            124,95
R5921C04F-K11          54,95             43,95
TID21C00I-A11          99,95             79,95
G1111A01Q-G11         149,95             90,00
CR221I07V-C11          59,95             35,95
S0011A00W-Q11         219,95            110,00
SE321S003-A11         209,95            135,95
TO311A012-O11          69,95             55,95
OA121U01Y-G11         229,95            148,95
PIG11N003-C11          69,99             28,00
WD221U03R-K11         259,95            193,55
GA111A0UT-C11         119,95             77,95
VE121G0OU-C11          29,99             24,00
NX321B026-Q12          22,00             11,00
VD211A00S-J11          79,95             63,95
DR221C00U-K11         149,95            119,95
5BI11B006-B11         119,95             95,95
MF921S03U-A11          41,95             29,36
AD741G01A-Q11         129,95             90,95
SG721C0BJ-J11         189,95            151,95
HU315A00N-A11          64,95             38,95
KP111A00F-F11          74,95             40,95
VEB21U00S-B11          64,99             48,45
M6429H05Z-A11          39,99             24,00
M3211A00K-Q11          49,99             29,99
ON511A006-Q12          29,99             15,00
KU011A01B-B11         159,95             80,00
C1181O00Q-G11          69,95             52,45

[74928 rows x 2 columns]

In [11]:
df['priceoriginal']=df['price_original'].str.replace(',','.').astype(float)
df['pricepromotional']=df['price_promotional'].str.replace(',','.').astype(float)
df[['priceoriginal','pricepromotional']]

               priceoriginal  pricepromotional
sku
UN241E0AV-Q11          44.95             40.00
M3221C0L6-O11          64.95             50.00
UN241I030-Q11          49.95             35.00
CO415N03F-A11          69.95             55.95
NI121A05R-Q11          24.95             20.00
NE211A094-D11          74.95             50.00
CO415B09I-A11          64.95             51.95
NI111A0D7-B11         109.95             75.00
AN611E015-Q11          39.99             39.99
NI121A09O-G11          39.95             36.00
RE011S03V-A11          69.95             59.45
NI121A09Q-Q11          34.95             31.00
PU111A0EB-Q11          60.00             25.00
AD115B01Y-A11          99.95             80.00
CO411A0BD-002          69.95             65.00
AN611A0A9-Q11          31.99             19.20
UN241G02V-Q11          69.95             56.51
UN241D00M-Q11          24.95             21.00
ZI111NA47-Q11         109.99             44.00
OY121C03G-G11          29.99             20.99
CO411A003-802          64.95             60.00
NE211A02Y-A11          99.95             70.55
PU111A0DP-A11          90.00             63.00
RE011S01A-A11          69.95             49.00
NL011A0LH-F11          14.99              9.00
NI111A0DD-K12         129.95             90.00
VE121N0DF-C11          34.99             22.75
1FI21D009-K12          34.95             27.95
C0T21D00P-Q11          44.95             31.00
AD121D0HV-Q11          24.95             21.00
...                      ...               ...
MT711A02Q-J11          54.95             43.95
M0Q21C11D-Q11          39.99             32.00
C0K21C03V-Q11         249.95            124.95
R5921C04F-K11          54.95             43.95
TID21C00I-A11          99.95             79.95
G1111A01Q-G11         149.95             90.00
CR221I07V-C11          59.95             35.95
S0011A00W-Q11         219.95            110.00
SE321S003-A11         209.95            135.95
TO311A012-O11          69.95             55.95
OA121U01Y-G11         229.95            148.95
PIG11N003-C11          69.99             28.00
WD221U03R-K11         259.95            193.55
GA111A0UT-C11         119.95             77.95
VE121G0OU-C11          29.99             24.00
NX321B026-Q12          22.00             11.00
VD211A00S-J11          79.95             63.95
DR221C00U-K11         149.95            119.95
5BI11B006-B11         119.95             95.95
MF921S03U-A11          41.95             29.36
AD741G01A-Q11         129.95             90.95
SG721C0BJ-J11         189.95            151.95
HU315A00N-A11          64.95             38.95
KP111A00F-F11          74.95             40.95
VEB21U00S-B11          64.99             48.45
M6429H05Z-A11          39.99             24.00
M3211A00K-Q11          49.99             29.99
ON511A006-Q12          29.99             15.00
KU011A01B-B11         159.95             80.00
C1181O00Q-G11          69.95             52.45

[74928 rows x 2 columns]

In [14]:
df['price_dif']=df['priceoriginal']-df['pricepromotional']
df['price_dif'].sort_values(ascending=False)

sku
23B21A005-J11    500.00
PAG21C00O-J11    490.00
IR221B006-J11    460.00
TI821C04A-I11    453.00
23B21C002-A11    450.00
MP421C014-A11    425.00
MP421C010-Q11    425.00
MRA21C00F-G11    425.00
SE321U000-N11    425.00
TI821C046-J11    408.00
MRA21C00E-K11    405.00
23B21T000-G11    400.00
PQ411B007-H11    399.95
PQ411A004-Q12    399.95
PQ411A004-D11    399.95
PQ411A004-A12    399.95
PQ411A004-D11    399.95
0VB21C00P-A11    398.00
MRA21A008-Q11    398.00
IR221B005-Q11    395.00
TI811N009-M11    380.00
MRA21A00B-B11    380.00
TI821G00C-J11    380.00
CE721C01F-Q11    379.95
DF221C00P-G11    375.00
MRA21J000-H11    353.00
E2121C044-Q11    350.00
PO221C04S-T11    350.00
PE441E00S-K11    350.00
PS721U00A-H11    340.00
                  ...
JO551Q004-D11      0.01
BI111D00K-G11      0.01
H0421D029-Q11      0.01
IC221G01V-Q11      0.01
EF329F05J-K11      0.01
FP081A031-J13      0.01
FP081A031-K12      0.01
9F029G00C-Q11      0.01
BI111D00M-I11      0.01
FS151F0CL-O11      0.01
H0421D029-K11      0.01
C1821N03R-K13      0.01
KA321C0BQ-K11      0.01
TI315B00H-A11      0.01
JO551Q003-D11      0.01
FS151F0CA-Q11      0.01
FS151F0CM-O11      0.01
DUB11E002-Q11      0.01
NI111A0BN-N11      0.01
23B21U00H-B11      0.00
AN611E015-Q11      0.00
TI821U007-O11   -240.05
DEA21L000-I11   -285.00
F1421U00H-A11   -295.00
FD521A00J-O11   -302.00
PO221C04T-T11   -325.00
TI821C043-Q11   -435.05
TI821C049-K11   -472.00
TI821U005-N11   -574.05
VEF51M00D-K11   -679.05
Name: price_dif, Length: 74928, dtype: float64

In [15]:
df['price_dif'].sum()

1912441.68