# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import your libraries:

import pandas as pd
import numpy as np
import scipy 
import sklearn

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [2]:
# Your code here:

from sklearn import datasets
diabetesDataset = datasets.load_diabetes()

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [3]:
# Your code here:

diabetesDataset.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [30]:
diabetesDataset

{'data': array([[ 1.        ,  0.03807591,  0.05068012, ..., -0.00259226,
          0.01990842, -0.01764613],
        [ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 1.        ,  0.08529891,  0.05068012, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 1.        ,  0.04170844,  0.05068012, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [ 1.        , -0.04547248, -0.04464164, ...,  0.02655962,
          0.04452837, -0.02593034],
        [ 1.        , -0.04547248, -0.04464164, ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - Age\n      - Sex\n      - Body mass index\n      - Average blood pressure\n      - S1\n      - S2\n      - S3\n      - S4\n      - S5\n      - S6\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttp://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(http://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'C:\\Users\\anast\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\diabetes_data.csv.gz',
 'target_filename': 'C:\\Users\\anast\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\diabetes_target.csv.gz'}

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [10]:
# Your code here:
diabetesDataset.DESCR

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - Age\n      - Sex\n      - Body mass index\n      - Average blood pressure\n      - S1\n      - S2\n      - S3\n      - S4\n      - S5\n      - S6\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttp://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(http://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)'

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here: Attribute Information:\n      - Age\n      - Sex\n      - Body mass index\n      - Average blood pressure\n      - S1\n      - S2\n      - S3\n      - S4\n      - S5\n      - S6\n\nNote

Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [13]:
# Your code here:

len(diabetesDataset.data)

442

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn.

In [14]:
# Your code here:

from sklearn.linear_model import LinearRegression

Initialize the model in the variable `diabetes_model`

In [15]:
# Your code here:
diabetes_model = LinearRegression().fit(diabetesDataset.data, diabetesDataset.target)

In the cell below, fit the model and print the intercept and coefficients of the model.

In [17]:
# Your code here:
diabetes_model.score(diabetesDataset.data, diabetesDataset.target)

0.5177494254132934

In [18]:
print(diabetes_model.intercept_, diabetes_model.coef_)

152.1334841628965 [ -10.01219782 -239.81908937  519.83978679  324.39042769 -792.18416163
  476.74583782  101.04457032  177.06417623  751.27932109   67.62538639]

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [22]:
# Your code here:

import statsmodels.api as sm
diabetesDataset.data = sm.add_constant(diabetesDataset.data)

#Note the swap of X and Y
model = sm.OLS(diabetesDataset.target, diabetesDataset.data).fit()

#Stats model gives better output
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Tue, 17 Sep 2019   Prob (F-statistic):           3.83e-62
Time:                        11:10:34   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        152.1335      2.576     59.061      0.000     147.071     157.196
x1           -10.0122     59.749     -0.168      0.867    -127.448     107.424
x2          -239.8191     61.222     -3.917      0.000    -360.151    -119.488
x3           519.8398     66.534      7.813      0.000     389.069     650.610
x4           324.3904     65.422      4.958      0.000     195.805     452.976
x5          -792.1842    416.684     -1.901      0.058   -1611.169      26.801
x6           476.7458    339.035      1.406      0.160    -189.621    1143.113
x7           101.0446    212.533      0.475      0.635    -316.685     518.774
x8           177.0642    161.476      1.097      0.273    -140.313     494.442
x9           751.2793    171.902      4.370      0.000     413.409    1089.150
x10           67.6254     65.984      1.025      0.306     -62.065     197.316
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [69]:
# Your code here:

auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [70]:
# Your code here:

auto.head()

,mpg,cylinders,displacement,horse_power,weight,acceleration,model_year,car_name
0,18.0,8,307.0,130.0,3504,12.0,70,"\t""chevrolet chevelle malibu"""
1,15.0,8,350.0,165.0,3693,11.5,70,"\t""buick skylark 320"""
2,18.0,8,318.0,150.0,3436,11.0,70,"\t""plymouth satellite"""
3,16.0,8,304.0,150.0,3433,12.0,70,"\t""amc rebel sst"""
4,17.0,8,302.0,140.0,3449,10.5,70,"\t""ford torino"""

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [80]:
# Your code here:

auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [81]:
# Your code here:

print(auto.model_year.min())
print(auto.model_year.max())

70
82

Check the dataset for missing values and remove all rows containing at least one missing value.

In [75]:
# Your code here:

auto.isnull().sum()
#auto=auto.dropna()

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [76]:
# Your code here:

auto.cylinders.value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [82]:
# Import the necessary function
#auto=auto.drop(['car_name'], axis=1)
auto.head()

,mpg,cylinders,displacement,horse_power,weight,acceleration,model_year
0,18.0,8,307.0,130.0,3504,12.0,70
1,15.0,8,350.0,165.0,3693,11.5,70
2,18.0,8,318.0,150.0,3436,11.0,70
3,16.0,8,304.0,150.0,3433,12.0,70
4,17.0,8,302.0,140.0,3449,10.5,70

In [83]:
# Your code here:

from sklearn.model_selection import train_test_split

In [38]:
X_train,X_test,y_train,y_test= train_test_split(auto.drop(columns='mpg', axis=1), auto.mpg, test_size=0.2, random_state=10)

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [39]:
# Your code here:
model = sm.OLS(y_train, X_train).fit()

Next, fit the model in the cell below.

In [40]:
# Your code here:

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.981
Method:                 Least Squares   F-statistic:                     2744.
Date:                Tue, 17 Sep 2019   Prob (F-statistic):          2.34e-263
Time:                        12:46:24   Log-Likelihood:                -825.64
No. Observations:                 313   AIC:                             1663.
Df Residuals:                     307   BIC:                             1686.
Df Model:                           6
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
cylinders       -0.7563      0.366     -2.065      0.040      -1.477      -0.036
displacement     0.0155      0.008      1.883      0.061      -0.001       0.032
horse_power     -0.0276      0.014     -1.975      0.049      -0.055    -9.8e-05
weight          -0.0064      0.001     -8.781      0.000      -0.008      -0.005
acceleration    -0.1115      0.101     -1.102      0.271      -0.311       0.088
model_year       0.6350      0.027     23.662      0.000       0.582       0.688
==============================================================================
Omnibus:                       34.704   Durbin-Watson:                   1.933
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               56.250
Skew:                           0.678   Prob(JB):                     6.10e-13
Kurtosis:                       4.572   Cond. No.                     5.83e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.83e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [44]:
#linear=LinearRegression().fit(X_train, y_train)
linear.score(X_train, y_train)

0.8129371960890941

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [50]:
# Import the necessary function:

y_pred = linear.predict(X_test)

In [51]:
y_pred

array([25.96977589, 31.39983507, 22.39944038, 35.30075368, 17.40014935,
       21.54510596, 17.2014747 ,  5.71415485, 31.01717172, 25.13936396,
       20.06751458, 20.46548475, 29.96347607, 31.17005808, 11.73968169,
       15.31971601, 21.58960231, 28.71960091,  8.78190759, 10.49889272,
       16.36404118, 31.48478253, 19.17955125, 16.38813389, 14.12100543,
        9.95360593, 17.08093041, 30.67481621, 24.19413668, 21.07878001,
       21.93224905, 23.79208468, 30.6243234 , 23.29162065, 24.36587834,
       30.1920512 , 31.82056356, 20.43999193, 15.56006078, 29.02224974,
       21.51727892, 22.1870461 , 32.25164699, 26.09103104, 22.46556718,
       11.60584406, 13.95830827, 34.56413288, 23.74032741, 29.41831581,
       25.83499212, 10.87353649, 21.51386016, 12.96835507, 14.37224893,
       29.11335128, 23.41491489, 25.77264603, 26.98465173, 27.09189484,
       32.10616278, 25.39595477, 21.11225063, 21.69696196, 30.44260865,
       27.54717952,  8.41481512, 26.47850346, 21.74783656, 12.83679974,
        8.77447371, 31.23093569, 27.00888657, 30.55473398, 31.00938432,
       21.89889871, 19.71805886, 15.28411112, 28.37541832])

In [52]:
y_test

243    21.5
371    29.0
300    23.9
345    35.1
265    17.5
263    17.7
214    13.0
44     13.0
326    43.4
57     24.0
128    15.0
154    15.0
397    31.0
388    26.0
62     13.0
66     17.0
101    23.0
183    25.0
26     10.0
6      14.0
229    16.0
278    31.5
48     18.0
213    13.0
1      15.0
67     11.0
133    16.0
279    29.5
283    20.2
24     21.0
       ...
240    30.5
114    26.0
106    12.0
100    18.0
140    14.0
12     15.0
389    22.0
169    20.0
79     26.0
111    18.0
255    25.1
303    31.8
132    25.0
228    18.5
99     18.0
390    32.0
53     31.0
103    11.0
327    36.4
209    19.0
65     14.0
27     11.0
337    32.4
271    23.2
216    31.5
301    34.2
120    19.0
98     16.0
190    14.5
102    26.0
Name: mpg, Length: 79, dtype: float64

In [54]:
# Your code here:
from sklearn.metrics import r2_score

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [53]:
# Your code here:

r2_score(y_test, y_pred)

0.7850623739534026

# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [84]:
# Your code here:

X_train,X_test,y_train,y_test= train_test_split(auto.drop(columns='mpg', axis=1), auto.mpg, test_size=0.1, random_state=10)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [85]:
# Your code here:

auto_model09=LinearRegression().fit(X_train, y_train)

Compute the predicted values and r squared score for our new model and new sample data.

In [86]:
y_test.shape

(40,)

In [87]:
# Your code here:
y_pred09 = linear.predict(X_test)

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [88]:
# Your code here:
r2_score(y_pred09,y_test)

0.7221942944692142

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [67]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [89]:
# Your code here:

selector=RFE(auto_model09,3)
selector.fit(X_train,y_train)
selector.ranking_

array([1, 2, 1, 3, 4, 1])

Fit the model and print the ranking

In [95]:
# Your code here:

model3=LinearRegression().fit(X_train[['cylinders', 'acceleration', 'model_year']], y_train)

In [96]:
y_pred_rfe=model3.predict(X_test[['cylinders', 'acceleration', 'model_year']])
y_pred_rfe

array([32.19564181, 32.64174129, 17.07420092, 31.85310169, 17.39478165,
       23.6537978 , 15.67562543, 12.1838543 , 30.09711877, 24.94881393,
       20.08650624, 20.34633149, 32.20321232, 32.83520995, 12.95959599,
       13.02408554, 19.43974365, 27.87120994, 11.02117528, 11.79504993,
       16.95438565, 29.68065154, 18.08172893, 16.06256276, 11.47260216,
       13.0885751 , 20.08650624, 29.46138706, 23.81043976, 17.24149769,
       21.84435619, 23.16367718, 32.30639561, 21.56060215, 23.22816674,
       28.77593074, 28.82938942, 15.0933524 , 13.67084813, 31.02576835])

In [97]:
r2_score(y_pred_rfe,y_test)

0.5434514138817731

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [202]:
# Your code here:

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [203]:
# Your code here: